### ISSUE TITLE
Datos de la empresa

### ISSUE THREAD

**Issue by danielarubialesmarquez** [danielarubialesmarquez/proyecto_final_3ro#3]
preguntar los datos mas importantes a la empresa

**Comment by GabiCuriel** [comment]
El negocio se encuentra ubicado en el municipio  de Santiago Tulantepec  en la localidad de Felipe Ángeles encontrando la fonda Mi abuelita que se dedica a la venta de antojitos mexicanos, llevando ya 10 años en el establecimiento cuya dueña es la señora Felipa Soto Rosales.
